#!/usr/bin/env python3
# poncelet — bake data/*.csv to a C++ source fragment.
# SPDX-License-Identifier: MIT
#
# Reads the four editable tables in data/ and emits src/generated/data_tables.inc,
# a plain-data C++ fragment included by src/catalog.cpp. The generated file is
# committed so a Python-less build still works; CMake re-runs this when a CSV or
# this script changes.
#
#   python3 tools/bake_data.py [--check]
#
# --check exits non-zero (without writing) if the committed .inc is stale.

import csv
import io
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "src" / "generated" / "data_tables.inc"


def rows(name):
    """Yield dict rows from a CSV, skipping '#' comment lines and blanks."""
    text = (DATA / name).read_text(encoding="utf-8")
    lines = [ln for ln in text.splitlines() if ln.strip() and not ln.lstrip().startswith("#")]
    return list(csv.DictReader(io.StringIO("\n".join(lines))))


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def num(s):
    s = (s or "").strip()
    return "0.0" if s == "" else repr(float(s))


def curve(s):
    """'x:y|x:y' -> list of (x, y) float pairs."""
    s = (s or "").strip()
    if not s:
        return []
    out = []
    for pair in s.split("|"):
        x, y = pair.split(":")
        out.append((float(x), float(y)))
    return out


def emit():
    buf = []
    w = buf.append
    w("// GENERATED by tools/bake_data.py from data/*.csv — DO NOT EDIT.")
    w("// Re-run `python3 tools/bake_data.py` after editing a data table.")
    w("// SPDX-License-Identifier: MIT")
    w("")
    w("namespace pon::detail {")
    w("")

    # --- class defaults ---
    cd = rows("class_defaults.csv")
    w("const RawClassDefault kRawClassDefaults[] = {")
    for r in cd:
        w("    {{ {}, {}, {}, {}, {}, {}, {}, {} }},".format(
            cstr(r["klass"]), num(r["ref_diameter_m"]), num(r["mass_kg"]),
            cstr(r["drag_model"]), num(r["drag_coefficient"]),
            num(r["ballistic_coefficient"]), num(r["muzzle_speed_mps"]),
            num(r["nose_shape_factor"])))
    w("};")
    w("const std::size_t kRawClassDefaultCount = {};".format(len(cd)))
    w("")

    # --- projectile catalog ---
    pr = rows("projectiles.csv")
    w("const RawProjectile kRawProjectiles[] = {")
    for r in pr:
        w("    {{ {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {} }},".format(
            cstr(r["id"]), cstr(r["klass"]), cstr(r["drag_model"]),
            num(r["mass_kg"]), num(r["ref_diameter_m"]),
            num(r["ballistic_coefficient"]), num(r["drag_coefficient"]),
            cstr(r["ball_profile"]), num(r["muzzle_speed_mps"]),
            num(r["nose_shape_factor"]), num(r["hardness"]),
            int(r["deformable"]), int(r["fragile"]),
            num(r["spin_rate_radps"]), cstr(r["spin_axis_mode"]),
            num(r["twist_rate_m"])))
    w("};")
    w("const std::size_t kRawProjectileCount = {};".format(len(pr)))
    w("")

    # --- ball profiles (curves emitted as their own arrays) ---
    bp = rows("ball_profiles.csv")
    for r in bp:
        for tag, col in (("cd", "cd_curve"), ("cl", "cl_curve")):
            pts = curve(r[col])
            if not pts:
                continue
            w("static const RawCurvePt kBP_{}_{}[] = {{ {} }};".format(
                r["id"], tag,
                ", ".join("{{ {}, {} }}".format(repr(x), repr(y)) for x, y in pts)))
    w("const RawBallProfile kRawBallProfiles[] = {")
    for r in bp:
        cd_pts, cl_pts = curve(r["cd_curve"]), curve(r["cl_curve"])
        cd_ref = ("kBP_{}_cd, {}".format(r["id"], len(cd_pts))) if cd_pts else "nullptr, 0"
        cl_ref = ("kBP_{}_cl, {}".format(r["id"], len(cl_pts))) if cl_pts else "nullptr, 0"
        w("    {{ {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {} }},".format(
            cstr(r["id"]), cstr(r["shape"]), num(r["diameter_m"]),
            num(r["mass_kg"]), num(r["typical_speed_mps"]), cstr(r["abscissa"]),
            cd_ref, cl_ref, num(r["cd_spiral"]), num(r["cd_tumble"]),
            num(r["spin_radius_m"])))
    w("};")
    w("const std::size_t kRawBallProfileCount = {};".format(len(bp)))
    w("")

    # --- materials ---
    mt = rows("materials.csv")
    w("const RawMaterial kRawMaterials[] = {")
    for r in mt:
        w("    {{ {}, {}, {}, {}, {}, {}, {}, {} }},".format(
            cstr(r["name"]), cstr(r["behaviour"]), num(r["density_kgm3"]),
            num(r["strength_pa"]), num(r["toughness_j_m2"]),
            num(r["thickness_m"]), num(r["elasticity"]),
            int(r["enters_medium"])))
    w("};")
    w("const std::size_t kRawMaterialCount = {};".format(len(mt)))
    w("")
    w("} // namespace pon::detail")
    w("")
    return "\n".join(buf)


def main():
    text = emit()
    if "--check" in sys.argv[1:]:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            print("data_tables.inc is stale — run: python3 tools/bake_data.py", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print("wrote", OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
