#!/usr/bin/env python3
# poncelet — generate the fixed-point transcendental LUTs for the BitExact core.
# SPDX-License-Identifier: MIT
#
# Emits src/generated/fixed_lut_tables.inc: uniform sample tables of the four
# transcendentals the integrator core (src/integrate.cpp) uses, stored as raw
# Q32.32 int64 values (raw = round(value * 2**32)). The runtime (src/fixed_lut.hpp)
# does a fixed-point linear interpolation between samples, so the tables are the
# ONLY place a platform libm could differ — committing them makes the result
# bit-identical everywhere.
#
# Tables:
#   sin        f(a)  = sin(a),           a in [0, pi]         (6-DOF yaw)
#   acos       f(c)  = acos(c),          c in [-1, 1]         (6-DOF angle of attack)
#   exp_neg    f(x)  = exp(-x),          x in [0, 32]         (analytic-drag fast path)
#   pow_neg017 f(s)  = (s*s)**(-0.17),   s in [0, 20]         (Litz spin-drift term,
#              sampled on s = sqrt(t) so the t->0 curvature is spread out and the
#              exact fixed-point sqrt from B3 supplies the abscissa)
#
# Re-run and commit the .inc after changing a domain or resolution:
#   python3 tools/gen_fixed_lut.py            # write
#   python3 tools/gen_fixed_lut.py --check    # verify committed copy is fresh
import math, os, sys

ONE = 1 << 32

def raw(v):
    return int(math.floor(v * ONE + 0.5)) if v >= 0 else -int(math.floor(-v * ONE + 0.5))

# (name, x0, x1, n_intervals, f)
TABLES = [
    ("sin",        0.0,  math.pi, 1024, lambda a: math.sin(a)),
    ("acos",      -1.0,  1.0,     1024, lambda c: math.acos(max(-1.0, min(1.0, c)))),
    ("exp_neg",    0.0,  32.0,    2048, lambda x: math.exp(-x)),
    # Sampled on w = t**0.25 (two nested exact sqrts) so the t→0 curvature is
    # spread wide; value is w**(-0.68) = t**(-0.17). w = 0 is singular, so
    # index 0 is clamped to the value at index 1. t ≤ 300 ⇒ w ≤ 4.16 < 4.5.
    ("pow_neg017", 0.0,  4.5,     2048, lambda w: w ** (-0.68) if w > 0 else 0.0),
]

def emit():
    out = []
    out.append("// GENERATED by tools/gen_fixed_lut.py — DO NOT EDIT.")
    out.append("// Re-run `python3 tools/gen_fixed_lut.py` after changing a domain/resolution.")
    out.append("// SPDX-License-Identifier: MIT")
    out.append("")
    out.append("namespace pon::detail {")
    out.append("")
    for name, x0, x1, n, f in TABLES:
        step = (x1 - x0) / n
        vals = []
        for i in range(n + 1):
            x = x0 + i * step
            if name == "pow_neg017" and i == 0:
                x = x0 + step
            vals.append(raw(f(x)))
        out.append(f"// {name}: x in [{x0}, {x1}], {n} intervals, {n + 1} samples")
        out.append(f"inline constexpr FxLutDesc kFxLut_{name} {{")
        out.append(f"    /*x0*/    {raw(x0)}LL,")
        out.append(f"    /*x1*/    {raw(x1)}LL,")
        out.append(f"    /*invStep*/ {raw(1.0 / step)}LL,")
        out.append(f"    /*n*/     {n},")
        out.append("};")
        out.append(f"inline constexpr long long kFxLutData_{name}[] = {{")
        for j in range(0, len(vals), 8):
            out.append("    " + ", ".join(f"{v}LL" for v in vals[j:j + 8]) + ",")
        out.append("};")
        out.append("")
    out.append("} // namespace pon::detail")
    out.append("")
    return "\n".join(out)

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    dst = os.path.join(here, "..", "src", "generated", "fixed_lut_tables.inc")
    text = emit()
    if "--check" in sys.argv:
        try:
            cur = open(dst, encoding="utf-8").read()
        except OSError:
            cur = None
        if cur != text:
            sys.stderr.write("fixed_lut_tables.inc is stale — re-run tools/gen_fixed_lut.py\n")
            sys.exit(1)
        print("fixed_lut_tables.inc is fresh")
        return
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {os.path.normpath(dst)}")

if __name__ == "__main__":
    main()
